version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: echo "Hello World !"
      - add_ssh_keys:
          fingerprints:
            - "0a:6b:92:c6:4a:39:6b:4f:50:ee:37:21:3a:ed:aa:00"
      - run:
          name: ダミー アーティファクトの作成
          command: |
            echo "my artifact file" > /tmp/artifact1.txt;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact2.txt;
      - store_artifacts:
          path: /tmp/artifact1.txt
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
          
      - run:
          name: Unit Test
          command: |
            echo "Start My Unit Test !"
            sudo pip3 install -r requirements.txt
            python -m unittest discover 
