  
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: echo "Hello World !"
      - run:
          name: Unit Test
          command: |
            echo "Start My Unit Test !"
            python -m unittest discover 